export type TaiwanEndemicBird = {
  id: number;
  chineseName: string;
  englishName: string;
  scientificName: string;
  habitat: string;
  habitatTag: "mountain-forest" | "mid-forest" | "lowland" | "stream" | "high-mountain";
  size: "小型鳥" | "中小型鳥" | "中型鳥" | "中大型鳥" | "大型鳥";
  colors: string[];
  fieldMarks: string;
  intro: string;
  imageTone: string;
};

const endemicBirdSeeds: Omit<TaiwanEndemicBird, "id">[] = [
  {
    chineseName: "臺灣山鷓鴣",
    englishName: "Taiwan Partridge",
    scientificName: "Arborophila crudigularis",
    habitat: "中低海拔闊葉林、林下灌叢與潮濕山坡",
    habitatTag: "mid-forest",
    size: "中型鳥",
    colors: ["褐", "灰", "白"],
    fieldMarks: "身形圓胖、尾短，常在林下活動，鳴聲比外觀更容易先被注意到。",
    intro: "臺灣山鷓鴣是低調的林下鳥，常藏在草叢與落葉層附近，適合用聲音與棲地一起建立辨識感。",
    imageTone: "from-stone-200 via-amber-50 to-white",
  },
  {
    chineseName: "黑長尾雉",
    englishName: "Mikado Pheasant",
    scientificName: "Syrmaticus mikado",
    habitat: "中高海拔森林、林道邊緣與箭竹草坡",
    habitatTag: "high-mountain",
    size: "大型鳥",
    colors: ["黑", "藍", "白"],
    fieldMarks: "雄鳥全身深色、尾羽極長；雌鳥褐色斑駁，仍保有大型雉類輪廓。",
    intro: "黑長尾雉也常被稱為帝雉，是台灣高山森林代表性特有種，觀察時要保持距離避免干擾。",
    imageTone: "from-slate-200 via-stone-100 to-white",
  },
  {
    chineseName: "藍腹鷴",
    englishName: "Swinhoe's Pheasant",
    scientificName: "Lophura swinhoii",
    habitat: "中低海拔森林、林道與溪谷附近",
    habitatTag: "mid-forest",
    size: "大型鳥",
    colors: ["藍", "黑", "白", "紅"],
    fieldMarks: "雄鳥藍黑色金屬光澤、白色背斑與紅色臉部裸皮明顯；雌鳥褐色保護色。",
    intro: "藍腹鷴是台灣最具代表性的森林雉類之一，常在清晨或傍晚沿林道邊覓食。",
    imageTone: "from-sky-100 via-white to-moss-50",
  },
  {
    chineseName: "臺灣竹雞",
    englishName: "Taiwan Bamboo Partridge",
    scientificName: "Bambusicola sonorivox",
    habitat: "低海拔丘陵、農村邊坡、竹林與灌叢",
    habitatTag: "lowland",
    size: "中型鳥",
    colors: ["褐", "棕", "灰"],
    fieldMarks: "身體圓胖、腿短，常成小群在地面行走，叫聲響亮連續。",
    intro: "臺灣竹雞常聽得到、未必看得到；對新手來說，先記住叫聲與地面活動習性很有幫助。",
    imageTone: "from-amber-100 via-white to-moss-50",
  },
  {
    chineseName: "五色鳥",
    englishName: "Taiwan Barbet",
    scientificName: "Psilopogon nuchalis",
    habitat: "低中海拔樹林、公園大樹與果樹周邊",
    habitatTag: "lowland",
    size: "中小型鳥",
    colors: ["綠", "紅", "黃", "藍"],
    fieldMarks: "全身綠色，頭臉有紅、黃、藍色斑塊，叫聲像規律敲木魚。",
    intro: "五色鳥色彩鮮明又常見，是台灣生活圈很適合入門的特有種。",
    imageTone: "from-emerald-100 via-lime-50 to-white",
  },
  {
    chineseName: "臺灣藍鵲",
    englishName: "Taiwan Blue Magpie",
    scientificName: "Urocissa caerulea",
    habitat: "低中海拔森林、林緣、山區聚落與公園",
    habitatTag: "mid-forest",
    size: "中大型鳥",
    colors: ["藍", "黑", "白", "紅"],
    fieldMarks: "藍色身體、黑頭、紅嘴紅腳，尾羽很長，常成群飛行。",
    intro: "臺灣藍鵲是辨識度很高的台灣特有種，但繁殖季具護巢行為，觀察時應保持距離。",
    imageTone: "from-cyan-100 via-white to-sky-100",
  },
  {
    chineseName: "赤腹山雀",
    englishName: "Chestnut-bellied Tit",
    scientificName: "Sittiparus castaneoventris",
    habitat: "中高海拔森林、針闊葉混合林與樹冠層",
    habitatTag: "high-mountain",
    size: "小型鳥",
    colors: ["黑", "白", "栗"],
    fieldMarks: "頭部黑白分明，腹部帶栗色，常在枝葉間快速移動。",
    intro: "赤腹山雀常混群活動，觀察時可以先從小型山雀輪廓和黑白頭紋開始辨認。",
    imageTone: "from-orange-100 via-white to-stone-100",
  },
  {
    chineseName: "黃山雀",
    englishName: "Yellow Tit",
    scientificName: "Machlolophus holsti",
    habitat: "中高海拔森林、樹冠層與林緣",
    habitatTag: "high-mountain",
    size: "小型鳥",
    colors: ["黃", "黑", "綠"],
    fieldMarks: "黃色腹部與黑色頭胸線醒目，常在樹冠間覓食。",
    intro: "黃山雀色彩鮮明，是山區賞鳥時很容易讓人驚喜的台灣特有種。",
    imageTone: "from-yellow-100 via-white to-lime-50",
  },
  {
    chineseName: "臺灣叢樹鶯",
    englishName: "Taiwan Bush Warbler",
    scientificName: "Locustella alishanensis",
    habitat: "中高海拔草叢、箭竹、灌叢與林緣",
    habitatTag: "high-mountain",
    size: "小型鳥",
    colors: ["褐", "棕", "灰"],
    fieldMarks: "外觀低調偏褐，常藏身草叢，辨識時很依賴鳴聲與棲地。",
    intro: "臺灣叢樹鶯不容易看清楚，適合提醒使用者鳥類辨識不只靠照片，也要重視聲音與環境。",
    imageTone: "from-stone-100 via-amber-50 to-white",
  },
  {
    chineseName: "臺灣鷦眉",
    englishName: "Taiwan Cupwing",
    scientificName: "Pnoepyga formosana",
    habitat: "潮濕山林、溪谷邊坡、蕨類與苔蘚覆蓋處",
    habitatTag: "stream",
    size: "小型鳥",
    colors: ["褐", "黑", "白"],
    fieldMarks: "體型很小、尾短，身上有細密斑紋，常貼近潮濕地表活動。",
    intro: "臺灣鷦眉是山林裡迷你又隱密的特有種，常需要耐心觀察林下動靜。",
    imageTone: "from-moss-100 via-white to-stone-100",
  },
  {
    chineseName: "烏頭翁",
    englishName: "Styan's Bulbul",
    scientificName: "Pycnonotus taivanus",
    habitat: "台灣東部與南部低海拔農地、聚落、公園與林緣",
    habitatTag: "lowland",
    size: "中小型鳥",
    colors: ["黑", "白", "灰"],
    fieldMarks: "黑色頭部、白色臉頰與灰褐身體，常與白頭翁作為比較對象。",
    intro: "烏頭翁是台灣低海拔生活圈的重要特有種，也常被拿來討論雜交與棲地變化議題。",
    imageTone: "from-zinc-200 via-white to-moss-50",
  },
  {
    chineseName: "褐頭花翼",
    englishName: "Taiwan Fulvetta",
    scientificName: "Fulvetta formosana",
    habitat: "中高海拔森林、灌叢與箭竹邊緣",
    habitatTag: "high-mountain",
    size: "小型鳥",
    colors: ["褐", "棕", "灰"],
    fieldMarks: "褐色頭部與細緻翼紋，常成群在灌叢間活動。",
    intro: "褐頭花翼是高山灌叢常見的小型特有種，適合練習觀察細部羽色與群體活動。",
    imageTone: "from-amber-100 via-white to-stone-100",
  },
  {
    chineseName: "冠羽畫眉",
    englishName: "Taiwan Yuhina",
    scientificName: "Yuhina brunneiceps",
    habitat: "中海拔森林、山區公路旁與開花結果植物附近",
    habitatTag: "mid-forest",
    size: "小型鳥",
    colors: ["褐", "白", "栗"],
    fieldMarks: "頭頂冠羽明顯，臉部白色與栗褐色形成對比，常成小群活動。",
    intro: "冠羽畫眉外型可愛、辨識度高，是台灣山區很受歡迎的特有種之一。",
    imageTone: "from-rose-50 via-white to-amber-100",
  },
  {
    chineseName: "小彎嘴",
    englishName: "Taiwan Scimitar Babbler",
    scientificName: "Pomatorhinus musicus",
    habitat: "低中海拔灌叢、竹林、林緣與山坡草叢",
    habitatTag: "mid-forest",
    size: "中小型鳥",
    colors: ["褐", "白", "黑"],
    fieldMarks: "嘴長而下彎，白眉線與臉部花紋清楚，常在灌叢中跳動。",
    intro: "小彎嘴的彎嘴輪廓是辨識重點，觀察時可先抓嘴型與白眉線。",
    imageTone: "from-stone-100 via-white to-moss-50",
  },
  {
    chineseName: "大彎嘴",
    englishName: "Black-necklaced Scimitar Babbler",
    scientificName: "Erythrogenys erythrocnemis",
    habitat: "中低海拔森林、濃密灌叢與林下",
    habitatTag: "mid-forest",
    size: "中型鳥",
    colors: ["褐", "白", "黑"],
    fieldMarks: "體型較大、嘴長下彎，頸胸黑色線條與臉部對比明顯。",
    intro: "大彎嘴比小彎嘴更壯、嘴更醒目，適合做大小與嘴型比較練習。",
    imageTone: "from-cream via-white to-stone-100",
  },
  {
    chineseName: "繡眼畫眉",
    englishName: "Morrison's Fulvetta",
    scientificName: "Alcippe morrisonia",
    habitat: "中海拔森林、林緣與灌叢",
    habitatTag: "mid-forest",
    size: "小型鳥",
    colors: ["褐", "灰", "白"],
    fieldMarks: "臉部有淡色眼圈感，整體灰褐，常在混群中快速穿梭。",
    intro: "繡眼畫眉外觀柔和低調，適合練習不要只看鮮豔顏色，也要看臉部比例與活動方式。",
    imageTone: "from-moss-100 via-white to-stone-100",
  },
  {
    chineseName: "臺灣噪眉",
    englishName: "White-whiskered Laughingthrush",
    scientificName: "Trochalopteron morrisonianum",
    habitat: "中高海拔森林、林道、箭竹與灌叢",
    habitatTag: "high-mountain",
    size: "中小型鳥",
    colors: ["褐", "灰", "白"],
    fieldMarks: "白色鬚狀臉部線條醒目，常成群在林下或路旁活動。",
    intro: "臺灣噪眉常在山區步道旁出現，群體活動和臉部白色線條是重要線索。",
    imageTone: "from-stone-100 via-white to-sky-50",
  },
  {
    chineseName: "白耳畫眉",
    englishName: "White-eared Sibia",
    scientificName: "Heterophasia auricularis",
    habitat: "中海拔森林、樹冠層與林緣花果植物",
    habitatTag: "mid-forest",
    size: "中小型鳥",
    colors: ["灰", "白", "黑"],
    fieldMarks: "白色耳羽斑非常明顯，尾長，常在樹冠層活動。",
    intro: "白耳畫眉的白耳斑很具代表性，是山區鳥類中容易建立視覺記憶的一種。",
    imageTone: "from-sky-50 via-white to-stone-100",
  },
  {
    chineseName: "紋翼畫眉",
    englishName: "Taiwan Barwing",
    scientificName: "Actinodura morrisoniana",
    habitat: "中高海拔森林、林緣灌叢與箭竹附近",
    habitatTag: "high-mountain",
    size: "中小型鳥",
    colors: ["褐", "栗", "灰"],
    fieldMarks: "翼上有細緻橫紋，尾較長，常在枝葉間成群移動。",
    intro: "紋翼畫眉適合練習看翼紋與尾型，常和其他山區混群鳥一起出現。",
    imageTone: "from-orange-100 via-white to-stone-100",
  },
  {
    chineseName: "黃胸藪眉",
    englishName: "Steere's Liocichla",
    scientificName: "Liocichla steerii",
    habitat: "中海拔森林、灌叢、林道邊與茶園邊緣",
    habitatTag: "mid-forest",
    size: "中小型鳥",
    colors: ["黃", "灰", "紅"],
    fieldMarks: "黃胸與紅色翼斑醒目，常在灌叢與林下快速移動。",
    intro: "黃胸藪眉色彩鮮明但行動敏捷，觀察時可先記住黃胸和翼上的紅色點綴。",
    imageTone: "from-yellow-100 via-white to-rose-50",
  },
  {
    chineseName: "臺灣畫眉",
    englishName: "Taiwan Hwamei",
    scientificName: "Garrulax taewanus",
    habitat: "低海拔灌叢、草坡、農地邊緣與次生林",
    habitatTag: "lowland",
    size: "中型鳥",
    colors: ["褐", "棕", "白"],
    fieldMarks: "褐色身體、眼周淡色線條，鳴聲響亮，常在灌叢中活動。",
    intro: "臺灣畫眉是低海拔灌叢代表性特有種，辨識時要注意與外來畫眉的差異。",
    imageTone: "from-amber-100 via-white to-moss-50",
  },
  {
    chineseName: "臺灣白喉噪眉",
    englishName: "Rufous-crowned Laughingthrush",
    scientificName: "Pterorhinus ruficeps",
    habitat: "中高海拔森林、箭竹、灌叢與林道旁",
    habitatTag: "high-mountain",
    size: "中小型鳥",
    colors: ["褐", "白", "栗"],
    fieldMarks: "白喉、栗色頭頂與褐色身體，常在灌叢裡成群活動。",
    intro: "臺灣白喉噪眉是山區常見的群居型特有種，聲音與活動方式都很有辨識價值。",
    imageTone: "from-rose-50 via-white to-amber-100",
  },
  {
    chineseName: "棕噪眉",
    englishName: "Rusty Laughingthrush",
    scientificName: "Pterorhinus poecilorhynchus",
    habitat: "中高海拔森林、濃密灌叢與林下",
    habitatTag: "high-mountain",
    size: "中小型鳥",
    colors: ["棕", "褐", "灰"],
    fieldMarks: "整體棕褐色，活動隱密，常靠聲音和灌叢動靜發現。",
    intro: "棕噪眉比鮮豔鳥種更考驗觀察耐心，適合練習從棲地與群體活動推測鳥種。",
    imageTone: "from-orange-100 via-white to-stone-100",
  },
  {
    chineseName: "火冠戴菊鳥",
    englishName: "Flamecrest",
    scientificName: "Regulus goodfellowi",
    habitat: "中高海拔針葉林、混合林與樹冠層",
    habitatTag: "high-mountain",
    size: "小型鳥",
    colors: ["黃", "橙", "綠"],
    fieldMarks: "體型極小，頭頂有橙黃色冠紋，常在樹冠快速覓食。",
    intro: "火冠戴菊鳥是台灣山林裡迷你卻亮眼的特有種，觀察時很考驗追焦與耐心。",
    imageTone: "from-yellow-100 via-white to-orange-100",
  },
  {
    chineseName: "白頭鶇",
    englishName: "White-headed Thrush",
    scientificName: "Turdus niveiceps",
    habitat: "中海拔森林、林下、林道與潮濕山坡",
    habitatTag: "mid-forest",
    size: "中型鳥",
    colors: ["白", "黑", "褐"],
    fieldMarks: "雄鳥白頭黑身對比明顯，雌鳥較褐，常在地面或低枝活動。",
    intro: "白頭鶇的雌雄差異明顯，適合練習把性別與年齡變異納入辨識。",
    imageTone: "from-zinc-100 via-white to-stone-100",
  },
  {
    chineseName: "黃腹琉璃",
    englishName: "Vivid Niltava",
    scientificName: "Niltava vivida",
    habitat: "中高海拔森林、溪谷、林道邊與陰濕林緣",
    habitatTag: "mid-forest",
    size: "中小型鳥",
    colors: ["藍", "黃", "褐"],
    fieldMarks: "雄鳥藍色上體與黃橙色腹部鮮明，雌鳥較低調偏褐。",
    intro: "黃腹琉璃色彩漂亮，但雌雄外觀差異大，適合提醒新手不要只背雄鳥照片。",
    imageTone: "from-cyan-100 via-white to-yellow-50",
  },
  {
    chineseName: "小翼鶇",
    englishName: "Taiwan Shortwing",
    scientificName: "Brachypteryx goodfellowi",
    habitat: "中高海拔潮濕林下、溪谷邊坡與濃密植被",
    habitatTag: "stream",
    size: "小型鳥",
    colors: ["褐", "灰", "藍"],
    fieldMarks: "尾短、身形低伏，常在林下陰暗處活動，雄鳥帶藍灰色調。",
    intro: "小翼鶇隱密又常在暗處，辨識時很需要環境、姿態與照片品質一起判斷。",
    imageTone: "from-slate-100 via-white to-moss-100",
  },
  {
    chineseName: "臺灣紫嘯鶇",
    englishName: "Taiwan Whistling Thrush",
    scientificName: "Myophonus insularis",
    habitat: "山區溪流、瀑布、潮濕岩壁與溪谷林道",
    habitatTag: "stream",
    size: "中型鳥",
    colors: ["藍", "紫", "黑"],
    fieldMarks: "全身深藍紫色金屬光澤，常在溪流岩石邊活動。",
    intro: "臺灣紫嘯鶇是溪流環境代表性特有種，深色身體和響亮鳴聲都很有印象。",
    imageTone: "from-indigo-100 via-white to-sky-100",
  },
  {
    chineseName: "臺灣白眉林鴝",
    englishName: "Taiwan Bush Robin",
    scientificName: "Tarsiger formosanus",
    habitat: "高海拔森林、箭竹、冷杉林緣與山徑旁",
    habitatTag: "high-mountain",
    size: "小型鳥",
    colors: ["藍", "橙", "白"],
    fieldMarks: "雄鳥白眉、藍色上體與橙色腹部明顯，常在低枝或地面附近活動。",
    intro: "臺灣白眉林鴝是高山賞鳥中很受喜愛的鳥，適合練習看眉斑和腹色。",
    imageTone: "from-sky-100 via-white to-orange-50",
  },
  {
    chineseName: "栗背林鴝",
    englishName: "Collared Bush Robin",
    scientificName: "Tarsiger johnstoniae",
    habitat: "高海拔針葉林、箭竹、林緣與山屋周邊",
    habitatTag: "high-mountain",
    size: "小型鳥",
    colors: ["栗", "白", "黑"],
    fieldMarks: "栗色背部、白色喉胸與深色頭部對比明顯，常在地面附近跳動。",
    intro: "栗背林鴝常出現在高山步道與林緣，是高海拔特有種觀察的經典目標。",
    imageTone: "from-orange-100 via-white to-stone-100",
  },
  {
    chineseName: "臺灣朱雀",
    englishName: "Taiwan Rosefinch",
    scientificName: "Carpodacus formosanus",
    habitat: "高海拔灌叢、箭竹草坡、冷杉林緣與開闊山坡",
    habitatTag: "high-mountain",
    size: "小型鳥",
    colors: ["紅", "褐", "灰"],
    fieldMarks: "雄鳥玫紅色調明顯，雌鳥較褐，嘴短厚呈雀科輪廓。",
    intro: "臺灣朱雀適合用嘴型、體型和高山棲地一起辨識，雌鳥不如雄鳥鮮豔。",
    imageTone: "from-rose-100 via-white to-stone-50",
  },
  {
    chineseName: "灰鷽",
    englishName: "Taiwan Bullfinch",
    scientificName: "Pyrrhula owstoni",
    habitat: "中高海拔森林、林緣與結實植物附近",
    habitatTag: "high-mountain",
    size: "小型鳥",
    colors: ["灰", "黑", "白"],
    fieldMarks: "嘴短厚、頭黑、身體灰色，常安靜停棲或取食植物種子。",
    intro: "灰鷽是台灣山區特有鳥類之一，辨識時可先看粗短嘴型和灰黑色調。",
    imageTone: "from-zinc-100 via-white to-sky-50",
  },
];

export const taiwanEndemicBirds: TaiwanEndemicBird[] = endemicBirdSeeds.map((bird, index) => ({
  ...bird,
  id: index + 1,
}));
